version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnetcoreapp
    container_name: dotnetcoreapp
    restart: unless-stopped
    ports:
      - "8080:80"
